Add Typography Component Group
abeg-help/frontend pull request #114
Opened 2023-11-09 10:52 UTC by GideonJesugbemi

## Description

Typography Component Group:

This component group is designed to leverage the @tailwindcss/typography plugin, enhancing the typographic capabilities of our project. The group will consist of the following components:

Title (new component)
TypographyWrapper (new component)

## Related Issue

- #108 

## Contribution Guidelines

Before submitting this pull request, please review our [Contribution Guidelines](https://github.com/abeg-help/frontend/blob/dev/CONTRIBUTING.md) to understand how to contribute to this project.

## Checklist

- I have reviewed the Contribution Guidelines linked above.
-  I have tested my changes thoroughly and ensured that all existing tests pass.
-  I have provided clear and concise commit messages.
-  I have updated the project's documentation as necessary.

## Screenshots (if applicable)

![TypographyWrapper](https://github.com/abeg-help/frontend/assets/105139480/be16e798-e4fc-45ae-845c-46637e201a4f)
![Title](https://github.com/abeg-help/frontend/assets/105139480/22bd5d22-17ef-48a2-8277-bc60ae3de4b5)

## Additional context (if needed)

2023-11-09 11:25 UTC, babblebey requested changes
Great stuff @GideonJesugbemi 

Kindly address the changes below.

...and yo, I seriously look forward to a demo of this 😉, this is because I expected a configuration of the `@tailwind/typography` plugin which should trigger a change in the `tailwind.config.ts` file.

So, I'm just super curious to know whether this component work without that configuration or did you forget to commit the config file???. 🤘🏾

2023-11-09 11:25 UTC, babblebey commented on primitives/TypographyWrapper.tsx
> +import React, { ReactNode } from 'react';
```suggestion
import React, { type ReactNode } from 'react';
```

When importing types, let's take the practice of prepending the `type` keyword to it, so to give cue of what it is.

2023-11-09 11:25 UTC, babblebey commented on primitives/Title.tsx
> +import React, { ReactNode } from 'react';
```suggestion
import React, { type ReactNode } from 'react';
```

Explicitly stating that the import is a `type`

2023-11-09 11:25 UTC, babblebey commented on primitives/TypographyWrapper.tsx
> +interface Iprops {
Do rename this interface to match the component name

2023-11-09 11:25 UTC, babblebey commented on primitives/TypographyWrapper.tsx
> +  size?: string;
Something is missing here 😉

The various sizes `sm | base | lg` etc...

2023-12-08 18:34 UTC, 289Volts approved these changes
Good job on this one

2023-12-08 18:34 UTC, merged